name: Dump Submodule Locations

on:
  push:
    branches:
      - main

jobs:
  dump-submodule-locations:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the main repository, including submodules
      - name: Check out repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive  # Ensure submodules are checked out
          fetch-depth: 0         # Fetch full history

      # Step 2: Generate JSON file with submodule folder locations
      - name: Generate submodule locations JSON
        run: |
          # Initialize an empty JSON array
          submodules_json="[]"

          # Loop through each submodule and record its folder path
          git submodule foreach --recursive '
            folder_path="$sm_path"
            submodules_json=$(echo $submodules_json | jq ". + [{\"name\": \"$folder_path\"}]")
          '

          # Output the generated JSON
          echo "$submodules_json" > submodules.json

      # Step 3: Commit and push submodules.json
      - name: Commit and push submodules.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add submodules.json
          git commit -m "Update submodule locations in submodules.json" || echo "No changes to commit"
          git push origin main
