name: Submodule Management

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Run daily at midnight UTC

jobs:
  manage-submodules:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the main repository, including submodules
      - name: Check out repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      # Step 2: Update all submodules
      - name: Update submodules
        run: |
          # Loop through each submodule and pull all branches
          git submodule foreach --recursive "
            echo 'Updating \$name in \$sm_path';
            git fetch --all;
            
            # Check if we're in a detached HEAD state and checkout the main branch
            if [ -z \"\$(git symbolic-ref --short HEAD 2>/dev/null)\" ]; then
              echo 'Detached HEAD detected, checking out main branch';
              git checkout main || git checkout master;
            fi;
            
            # Pull the latest changes
            git pull;
          "

      # Step 3: Generate JSON file with submodule information
      - name: Generate submodule information JSON
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Initialize an empty JSON array
          submodules_json="[]"
          
          # Get the owner/organization name from the repository URL
          owner=$(git config --get remote.origin.url | sed -n 's/.*github.com[:\/]\([^\/]*\)\/.*/\1/p')
          
          # Loop through each submodule
          while IFS= read -r line; do
            path=$(echo "$line" | awk '{print $2}')
            url=$(git config --file .gitmodules --get "submodule.$path.url")
            
            repo=$(basename "$url" .git)
            github_url="https://github.com/$owner/$repo"
            
            cd "$path"
            
            last_commit_hash=$(git rev-parse HEAD)
            last_commit_message=$(git log -1 --pretty=%B)
            last_commit_date=$(git log -1 --format=%cd --date=iso)
            last_updated=$(git log -1 --format=%cd --date=iso)
            
            # Get README content
            readme_content=""
            if [ -f "README.md" ]; then
              readme_content=$(cat README.md)
            elif [ -f "README" ]; then
              readme_content=$(cat README)
            fi
            
            cd - > /dev/null
            
            repo_info=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/$owner/$repo")
            
            description=$(echo "$repo_info" | jq -r '.description // "No description available"')
            
            submodules_json=$(echo $submodules_json | jq ". + [{
              \"name\": \"$path\",
              \"description\": \"$description\",
              \"githubUrl\": \"$github_url\",
              \"lastCommit\": {
                \"hash\": \"$last_commit_hash\",
                \"message\": \"$(echo "$last_commit_message" | sed 's/"/\\"/g')\",
                \"date\": \"$last_commit_date\",
                \"url\": \"$github_url/commit/$last_commit_hash\"
              },
              \"lastUpdated\": \"$last_updated\",
              \"readme\": \"$(echo "$readme_content" | sed 's/"/\\"/g')\"
            }]")            
          done < <(git config --file .gitmodules --get-regexp path)
          
          echo "$submodules_json" > submodules.json

      # Step 4: Commit and push all changes
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add submodules.json
          git add .
          git commit -m "Update submodules and submodule information" || echo "No changes to commit"
          git push origin main
