name: Submodule Management

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Run hourly

jobs:
  manage-submodules:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the main repository, including submodules
      - name: Check out repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      # Step 2: Update all submodules
      - name: Update submodules
        run: |
          # Loop through each submodule and pull all branches
          git submodule foreach --recursive "
            echo 'Updating \$name in \$sm_path';
            git fetch --all;
            
            # Check if we're in a detached HEAD state and checkout the main branch
            if [ -z \"\$(git symbolic-ref --short HEAD 2>/dev/null)\" ]; then
              echo 'Detached HEAD detected, checking out main branch';
              git checkout main || git checkout master;
            fi;
            
            # Pull the latest changes
            git pull;
          "

      # Step 3: Generate JSON file with submodule information
      - name: Generate submodule information JSON
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Initialize an empty JSON array
          echo '[]' > submodules.json
          
          # Get the owner/organization name from the repository URL
          owner=$(git config --get remote.origin.url | sed -n 's/.*github.com[:\/]\([^\/]*\)\/.*/\1/p')
          
          # Loop through each submodule
          while IFS= read -r line; do
            path=$(echo "$line" | awk '{print $2}')
            url=$(git config --file .gitmodules --get "submodule.$path.url")
            
            repo=$(basename "$url" .git)
            github_url="https://github.com/$owner/$repo"
            
            cd "$path" || continue
            
            last_commit_hash=$(git rev-parse HEAD)
            # Safely get commit message with fallback
            last_commit_message=$(git log -1 --pretty=%B || echo "No commit message") 
            last_commit_message=$(echo "$last_commit_message" | jq -R -s '.')
            last_commit_date=$(git log -1 --format=%cd --date=iso)
            last_updated=$(git log -1 --format=%cd --date=iso)
            
            # Get README content with safe fallbacks
            readme_content="No README available"
            if [ -f "README.md" ] && [ -s "README.md" ]; then
              readme_content=$(cat README.md | jq -R -s '.')
            elif [ -f "README" ] && [ -s "README" ]; then
              readme_content=$(cat README | jq -R -s '.')
            fi
            
            cd - > /dev/null
            
            # Safely get repository info with fallback
            repo_info=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/$owner/$repo")
            
            description=$(echo "$repo_info" | jq -r '.description // "No description available"')
            description=$(echo "$description" | jq -R -s '.')
            
            # Create temporary JSON file for this entry
            echo "{
              \"name\": \"$path\",
              \"description\": ${description},
              \"githubUrl\": \"$github_url\",
              \"lastCommit\": {
                \"hash\": \"$last_commit_hash\",
                \"message\": ${last_commit_message},
                \"date\": \"$last_commit_date\",
                \"url\": \"$github_url/commit/$last_commit_hash\"
              },
              \"lastUpdated\": \"$last_updated\",
              \"readme\": ${readme_content}
            }" | jq '.' > temp_entry.json
            
            # Append to main JSON array if valid
            if jq '.' temp_entry.json >/dev/null 2>&1; then
              jq -s '.[0] + [.[1]]' submodules.json temp_entry.json > temp_submodules.json && \
              mv temp_submodules.json submodules.json
            else
              echo "Warning: Invalid JSON generated for $path, skipping..."
            fi
            
            rm -f temp_entry.json
            
          done < <(git config --file .gitmodules --get-regexp path)

      # Step 4: Commit and push all changes
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add submodules.json
          git add .
          git commit -m "Update submodules and submodule information" || echo "No changes to commit"
          git push origin main
