name: Update Submodules

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the main repository, including submodules
      - name: Check out repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive # Ensure submodules are checked out
          fetch-depth: 0        # Fetch full history

      # Step 2: Update all submodules
      - name: Update submodules
        run: |
          # Loop through each submodule and pull all branches
          git submodule foreach --recursive "
            echo 'Updating \$name in \$sm_path';
            git fetch --all;
            
            # Check if we're in a detached HEAD state and checkout the main branch
            if [ -z \"\$(git symbolic-ref --short HEAD 2>/dev/null)\" ]; then
              echo 'Detached HEAD detected, checking out main branch';
              git checkout main || git checkout master;
            fi;
            
            # Pull the latest changes
            git pull;
          "

      # Step 3: Fetch the latest changes from the remote repository
      - name: Fetch and merge remote changes
        run: |
          git fetch origin
          git merge origin/main || git merge --strategy=recursive -X theirs origin/main # Handle any conflicts automatically

      # Step 4: Commit and push updated submodule references
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update submodules to latest commits" || echo "No changes to commit"
          git push origin main
