name: Update Submodules

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the main repository, including submodules
      - name: Check out repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive # Ensure submodules are checked out
          fetch-depth: 0        # Fetch full history to avoid issues

      # Step 2: Update all submodules to their latest commits
      - name: Update submodules
        run: |
          git submodule foreach 'git pull origin main'

      # Step 3: Commit and push updated submodule references
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update submodules to latest commits" || echo "No changes to commit"
          git push origin main
